config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  root :to => redirect('/ideas')
  resources :ximes
  resources :ideas

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/xime.rb
class Xime < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/ximes_controller.rb
class XimesController < ApplicationController
  before_action :set_xime, only: [:show, :edit, :update, :destroy]

  # GET /ximes
  # GET /ximes.json
  def index
    @ximes = Xime.all
  end

  # GET /ximes/1
  # GET /ximes/1.json
  def show
  end

  # GET /ximes/new
  def new
    @xime = Xime.new
  end

  # GET /ximes/1/edit
  def edit
  end

  # POST /ximes
  # POST /ximes.json
  def create
    @xime = Xime.new(xime_params)

    respond_to do |format|
      if @xime.save
        format.html { redirect_to @xime, notice: 'Xime was successfully created.' }
        format.json { render :show, status: :created, location: @xime }
      else
        format.html { render :new }
        format.json { render json: @xime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ximes/1
  # PATCH/PUT /ximes/1.json
  def update
    respond_to do |format|
      if @xime.update(xime_params)
        format.html { redirect_to @xime, notice: 'Xime was successfully updated.' }
        format.json { render :show, status: :ok, location: @xime }
      else
        format.html { render :edit }
        format.json { render json: @xime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ximes/1
  # DELETE /ximes/1.json
  def destroy
    @xime.destroy
    respond_to do |format|
      format.html { redirect_to ximes_url, notice: 'Xime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xime
      @xime = Xime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xime_params
      params.require(:xime).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ximes_helper.rb
module XimesHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.picture %></td>
          <td><%= link_to ' ', idea, :class=>"glyphicon glyphicon-eye-open iconsize" %></td>
        <td><%= link_to '', idea, :class=>"glyphicon glyphicon-pencil iconsize" %></td>
        <td><%= link_to '', idea, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'glyphicon glyphicon-trash iconsize' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<span class="glyphicon glyphicon-tree-deciduous" aria-hidden="true"></span>
<p> Actualmete hay <%= Idea.count %> ideas activas </p>
<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture_url, :width => 600) if @idea.picture? %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Idea app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
    <li class="<%= 'active' if current_page?(ideas_path) %>">
      <%= link_to 'Ideas', ideas_path %>
      </li>
    <li class="<%= 'active' if current_page? (pages_info_path) %>">
      <%= link_to '¿Quién soy?', pages_info_path %>
    </li>
      <li class="<%= 'active' if current_page? (new_idea_path) %>">
        <%= link_to 'Nueva Idea', new_idea_path %>
      </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<footer>
  <div class="container">
    Rails Girls 2016
  </div>
</footer>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/info.html.erb
<h1>Cambio Climatico</h1>

<p>La energía recibida por la Tierra desde el Sol, debe estar en balance con la radiación emitida desde la superficie terrestre, o sea, debe haber un equilibrio energético. Cualquier factor que genere un cambio sostenido entre la cantidad de energía que entra al sistema (en este caso la Tierra y su atmósfera) y la energía que salen del sistema, puede generar un cambio climático.</p>

app/views/ximes/_form.html.erb
<%= form_for(@xime) do |f| %>
  <% if @xime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@xime.errors.count, "error") %> prohibited this xime from being saved:</h2>

      <ul>
      <% @xime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ximes/edit.html.erb
<h1>Editing Xime</h1>

<%= render 'form' %>

<%= link_to 'Show', @xime %> |
<%= link_to 'Back', ximes_path %>

app/views/ximes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ximes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ximes.each do |xime| %>
      <tr>
        <td><%= xime.name %></td>
        <td><%= xime.description %></td>
        <td><%= xime.picture %></td>
        <td><%= link_to 'Show', xime %></td>
        <td><%= link_to 'Edit', edit_xime_path(xime) %></td>
        <td><%= link_to 'Destroy', xime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xime', new_xime_path %>

app/views/ximes/new.html.erb
<h1>New Xime</h1>

<%= render 'form' %>

<%= link_to 'Back', ximes_path %>

app/views/ximes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @xime.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @xime.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @xime.picture %>
</p>

<%= link_to 'Edit', edit_xime_path(@xime) %> |
<%= link_to 'Back', ximes_path %>